# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "argz-0.0.0--t7AWiiuAAAZTPjb_cxa3aELx-2Mkan4uwg3LDfSyu2H";
    path = fetchzip {
      url = "https://github.com/andrewkreuzer/argz/archive/59b48d7d4e3f8038aa4d43c739704e99113622d8.tar.gz";
      hash = "sha256-udsGidicgktFm/8oqN6LLAGqu4BGkk6BuN2nIpvmlOI=";
    };
  }
]
